services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      
    volumes:
      - /home/cristianl0pez/server-flix/config:/config
      - /home/cristianl0pez/server-flix/Series:/data/tvshows
      - /home/cristianl0pez/server-flix/Peliculas:/data/movies
      - /home/cristianl0pez/server-flix/Animes:/data/Animes
      
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
      - /dev/dri:/dev/dri #optional
     
    restart: unless-stopped