version: "2.1"
services:
  jellyfin:
    image: linuxserver/jellyfin
     container_name: jellyfin
      environment:
      - PUID=1000
      - PGID=1000
      - TZ= America/Santiago
      volumes:
      - ./home/cristianl0pez/server-flix/Anime
      - ./home/cristianl0pez/server-flix/Peliculas
      - ./home/cristianl0pez/server-flix/Series
      ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    devices:
    restart: unless-stopped